[package]
name = "vaktisalah-gtk-rs"
version = "2.0.0"
edition = "2021"

[profile.release]
strip = true
opt-level = 3
codegen-units = 1
lto = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# GTK
relm4 = { git = "https://github.com/Relm4/Relm4.git", branch="main", features = ["libadwaita", "macros", "gnome_43"] }
tokio = { version = "1.28", features = ["fs", "time"]}

# HTTP Request
reqwest = { version = "0.11", default-features = false, features = ["blocking", "json"] }

# Timing
chrono = "0.4.24"

# JSON Parsing
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Audio Playing
rodio = { version = "0.17.1", default-features = false, features = ["vorbis"] }

# Dirs
dirs = "5.0.0"

# Utils
once_cell = "1.17"
rust-i18n = { version= "2", default-features = false }
current_locale = "*"
tracker = "0.2.1"