[package]
name = "vaktisalah-gtk-rs"
version = "1.0.0"
edition = "2021"

[profile.release]
strip = true
opt-level = 3
codegen-units = 1

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# GTK
adw = { version = "0.4.1", package = "libadwaita" }
gtk4 = { version = "0.6.4", features = ["gnome_42"] }
glib = { version = "0.17.5" }
gio = { version = "0.17.4" }

# HTTP Request
reqwest = { version = "0.11", default-features = false, features = ["blocking", "json"] }

# Timing
chrono = "0.4.24"

# JSON Parsing
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Audio Playing
rodio = { version = "0.17.1", default-features = false, features = ["vorbis"] }

# Dirs
dirs = "5.0.0"

# Utils
once_cell = "1.17"
simple-localization = "0.2"